version: "3.7"

services:
  db:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: qwerty1234
      MONGODB_DATABASE: test
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_ADVERTISED_HOSTNAME: localhost